name: to_do_list
description: "A app to note To-Do list"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_slidable: ^3.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_chat_core: ^2.4.0
  flutter_chat_ui: ^2.3.1
  google_gemini: ^0.1.2
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  flutter_gemini: ^3.0.0

  # device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.3
  # device_preview: ^1.2.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

assets:
  - fonts/
  - .env

fonts:
  - family: Outfit
    fonts:
      - asset: assets/Outfit-Regular.ttf
      - asset: assets/Outfit-Bold.ttf
      - asset: assets/Outfit-Light.ttf
      - asset: assets/Outfit-Medium.ttf
      - asset: assets/Outfit-SemiBold.ttf
      - asset: assets/Outfit-ExtraBold.ttf
      - asset: assets/Outfit-Black.ttf

  - family: Satoshi
    fonts:
      - asset: assets/
